#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-delegation-update';

event_actions($event, 'initialize-default-databases' => '00');

foreach my $event (qw ( nethserver-delegation-update nethserver-delegation-save)) {
templates2events("/usr/share/nethesis/NethServer/Authorization/DelegatedPanel.json",  $event);
templates2events("/etc/sudoers.d/GroupDelegation",  $event);
templates2events("/etc/sudoers.d/UserDelegation",  $event);
}
