#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-delegated-panel-update';

event_actions($event, 'initialize-default-databases' => '00');
templates2events("/usr/share/nethesis/NethServer/Authorization/base.json",  $event);

foreach my $event (qw ( user-create user-modify)) {
templates2events("/usr/share/nethesis/NethServer/Authorization/base.json",  $event);
}
